### ISSUE TITLE
 Update to Pulsar client 3.0

### ISSUE THREAD

**Issue by onobc** [spring-projects/spring-pulsar#393]
This updated version shades the `javax.xml.bind:jaxb-api` library. This change [is required](https://github.com/spring-projects/spring-boot/pull/34763#discussion_r1167039098) in order for Spring Pulsar to be accepted into Spring Boot 3.2.

The Pulsar client 3.0 schedule is as follows:
- 2023-04-11 - RC-1
- 2023-04-18 - RC-2
- 2023-04-25 - RC-3
- 2023-05-02 - GA

### Todos
- [x] Identify and cleanly isolate any required code changes. 
- [x] Spring Pulsar must be usable for both 2.x and 3.x clients.
- [x] Add compatability matrix to docs
- [x] #411

**Comment by onobc** [comment]
It is now available https://github.com/apache/pulsar/releases/tag/v3.0.0 🎉

**Comment by onobc** [comment]
Closed via https://github.com/spring-projects/spring-pulsar/commit/9f2b2844afab7f51d70ace655e33b7afd65a3786
